baseURL = "https://libgeos.org/"
languageCode = "en-us"
title = "GEOS"
theme = "hugo-geekdoc"
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true
enableEmoji = true

enableGitInfo = false

[params]
  current_release = "3.13.1"
  geekdocLogo = "web-logo.png"

  # turn these on when we move to the gh/main branch
  geekdocRepo = "https://github.com/libgeos/geos"
  geekdocEditPath = "edit/main/web/content"

  geekdocBackToTop = true
